# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dictionary.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dictionary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64ictionary.proto\x12\ndictionary\"(\n\tWordCount\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\x1b\n\x0bWordRequest\x12\x0c\n\x04word\x18\x01 \x01(\t\"\x1d\n\x0cWordResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"\x0e\n\x0c\x45mptyRequest\":\n\x12\x44ictionaryResponse\x12$\n\x05words\x18\x01 \x03(\x0b\x32\x15.dictionary.WordCount2\xa2\x01\n\x11\x44ictionaryService\x12>\n\x07\x41\x64\x64Word\x12\x17.dictionary.WordRequest\x1a\x18.dictionary.WordResponse\"\x00\x12M\n\x0fPrintDictionary\x12\x18.dictionary.EmptyRequest\x1a\x1e.dictionary.DictionaryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dictionary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORDCOUNT']._serialized_start=32
  _globals['_WORDCOUNT']._serialized_end=72
  _globals['_WORDREQUEST']._serialized_start=74
  _globals['_WORDREQUEST']._serialized_end=101
  _globals['_WORDRESPONSE']._serialized_start=103
  _globals['_WORDRESPONSE']._serialized_end=132
  _globals['_EMPTYREQUEST']._serialized_start=134
  _globals['_EMPTYREQUEST']._serialized_end=148
  _globals['_DICTIONARYRESPONSE']._serialized_start=150
  _globals['_DICTIONARYRESPONSE']._serialized_end=208
  _globals['_DICTIONARYSERVICE']._serialized_start=211
  _globals['_DICTIONARYSERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
